### ISSUE TITLE
Interested in a version of parsy with type annotations?

### ISSUE THREAD

**Issue by denisrosset** [python-parsy/parsy#64] opened 2022-06-03 11:18 UTC
I had a look at the code base, it shouldn't be too difficult to add type annotations. I'd be happy to make a PR in that direction.

- Is there interest in that direction?
- If typing the code requires breaking changes or bumping the minimal Python version (I don't see why, but you never know), would you prefer releasing a new major version, or that I fork the library?

**Comment by spookylukey** [comment] 2022-09-06 13:07
Sorry I didn't see this earlier, I don't seem to be getting any notifications for this repo.

The problem is, type checking in Python currently works very badly with any dynamic tricks, and Parsy uses enough to defeat type checkers.

Of course, you can add some basic types for methods, but nothing that will really help you. I mean, a type checker could make sure that you were only calling `.parse()` or `.parse_partial()` on something that had those methods, but you typically call those very few times.

What you actually want is that in the following code, `my_val` should be accepted, but `my_val_2` should be rejected. 
```python
import parsy

my_val: int = parsy.regex(r"\d+").map(int).parse("1234")
my_val_2: int = parsy.regex(r"\d+").parse("1234")

```

For this, we need parsers that are generic in their output types. Without this, type annotations are pretty useful - yes we can say that we've got some `Parser` instances, but we don't know what they produce or how they can be chained together, which is 90% of what you do with Parsy code.

You can see my attempt to do this in https://github.com/python-parsy/parsy/pull/58 
I got quite far, but then it all comes unstuck for `seq` and `alt`. And those are pretty essential.

If you can do better, please let me know!

**Comment by spookylukey** [comment] 2022-11-10 11:30
I've created an experimental fork of parsy with an attempt at this: https://github.com/python-parsy/typed-parsy

The results are interesting - it's impressive what you can get mypy/pyright to check for you, but the code is much less readable. I'll be blogging about it soon.

**Comment by spookylukey** [comment] 2022-11-21 22:12
See my blog post:

https://lukeplant.me.uk/blog/posts/python-type-hints-parsy-case-study/

I've also added basic type hints to master in #69 but not a `py.typed` file, as described in the blog post. 

For these reasons I'm closing the ticket, but your feedback would still be appreciated.

**Closed by spookylukey** 2022-11-21 22:12 UTC
